language: node_js
node_js:
- '12'
- '14'
services:
- redis-server
script:
- echo 'Starting'
- npm install
- echo 'Testing'
- npm test
deploy:
  provider: heroku
  apy_key:
    secure: wxt5m2nAk+B8EEFpWH1CbScYve4TX5VpVczKld/yMy+iPJGR8vfCEht65ETm+NbUSr3b0nymaa0jOMPQF1OdnztfRwEG7/koAFuGeiJ1prI1hqFv6S5hzM79XFcmnEJafM+mSNEU1CFcCmvnf9dIDj/TsKNR5e+dgOy7NtsXsIExllfzViztKnMLWprC6xNZOl56HJi9mfRniO4SHIjcPvo7qIJgPfjTg5ulaTbeccp6teqLVudFKrFYZ7L5mMS48HH8iKw20RRJsYSjf3OJs6mxHRVjzIumMbqCXZrsgJjExVGppSbdjHkgajHC+IuLBu4a/74n+HieiN3juS2LZqsug2j6lS9YQSsTVP4v8oc4kWjuUPYabiK1BivL1wSMPo7ygJP8whJvOIaYRNkXuO0ZhEJmXicOEuZbg9/bU1cclxLhwmor2wstClcR7eFxv12jH2vDpVhujDrQchKWOS5m12JTEJ0tLdOwN1T3NoZQdUdpYLxWUnn0fDfkb7I4EzpdirVaL8h8v0h4UmbqzzRyfQPb608sLWl67zpggodXaNXe18rAqr39bsqs0y1OSSzAll+7CZxT155Ic43YQGiEWtdjhg32V8jOFiAQC3vz4hRISFz6/s3eMxLcz2VBbGZ71nzK+9fc7gjaOw2e/uJ5wmacOYW6W5hv5fxBkTM=