language: node_js
node_js:
- '12'
- '14'
services:
- redis-server
script:
- echo 'Starting'
- npm install
- echo 'Testing'
- npm test
deploy:
  provider: heroku
  apy_key:
  - secure: cDYej12SR/5fTUaHXSLjFFCO7hR5Cw2SkSFwa+bIT1d/nVQ22tEZKreeySgHay5WT9ntLBoGp/nwcfBY3I2UIVXMF2mAdAc3YkiGW+/AYJuvOIBqCQsR7rhxilHg6XF566l9EUM045vVkjqKvZzivh9OMJwFJ+CqJHKgssexPpBEdJbwtaxqZ8ojgJIP2RCAy6dKJQyHgPzEklBBkhSWVKKpu0QE16Bkm6+8CdiZuSJ+vW71XosOBh8FeGCjaLSE8WABgHSYPJW/t2MtQRy8hk/6rRsYpt3xfKbpADq91zhZ5lFRMRLF97ltkPIJ4p21cSXNjwmjZd8eV1yUPP9NMRoEEyp5Sb5oddjwsKzgoI5jryqjhblGKNO+Qk6/lB23eksIwd/rmgG4nZ5dunkKfGocOXtNi9Skyon5CXaovjraaVDArq1o3c83j+3i+v0l29X381UkgZm7AzdtdLvvP/DelWMfbuZravoQbqBG7qdbdELzozm7Pn72ehHVMfBoGBJiCIYtOCKCid6MruIpqFTBYpw7A5INc2aAmzCmzmGGYW55lU3orPovj+8rOO+zvH5++thwZyvG3mxlXsTi6eLF3DjDtrMR/g7pSFvuqaJ3iKsD7R3IxLiol2p7tzmk9BKp1RQ7UjpEooPB/86jWtYrL9FuHeSShybKWmG2ivQ=
  - secure: VFtBFgTD0DeT/c+le0yhuh+eJsHvTyhRBf72Rc4YLTE3QfpEAejSFOa2z11tCpvBbAI17OrDybr16jqnUEGjQBSngXLnk/sGqd+cxDqy+DfKnzcQLmgREW5uJsHDVELxCP2V9zw5m/IxoaKDdLRHnLQqjcV6kkDAyEq/pc6riZcqs8NdOxtVkSAc3ezcdss1EWrx8mwfPGePOtXYGVV9+6S2ntdkT00HWNy8jFrQmX1vKN4umlbnLjynH749MC1KhpvRDSrT0U9biyFnH8zBrfbDbL7p4HwbcFDUHyKq9eNlQKx/uLJAWdSvQtC32n8D8KsOH/CQbBiGkTEc4dfET7DqmqOy9ohYpl+hRRxpcMAa9vhJYixGbsWSciRreqdTrN0dME3zcA+nrX6/hbn9rzSOqQJK3pBBxpfmvQv3imMyQe9qmRvqBsq9baobKlA4G5ZiejU7ePnsHg6FrYfwP/6/pwr1aVbGTvK/yLb/vX2u2KFbMvzNQlxNXL/m/GEX32tfzGIgLuQ1hekMuAtBVkvciqfYKg5wl+2SXnNJ2VC1567iwLDkINCKvwHaE7i6tzeZ9X5SwZZuxF7pBqpI01imdvP+Be4BJ2auUyz9pIrr/SWRbvBqGXL03OVBc6W0ZYqbJ/BAWIBfo5b5u4ZML84xYwZkqpBJjQ+Wt3lL/H8=
