language: node_js
node_js:
- '12'
- '14'
services:
- redis-server
script:
- echo 'Starting'
- npm install
- echo 'Testing'
- npm test
deploy:
  provider: heroku
  api_key:
    secure: ZOwxXgQr5KzXp75vOi9IM2jnTo24tbYaFVWz7pttAvFkKM49GCR7Rv0Een/mraIyUWYuivryuAKi9WgoU5RaXzh7H65cat9R1dyYybO/eizUsxH3AateNUev/ULj7x9s74zAs9GBE6vRA6ZJZ8icLZAba/y1PGIzP71ofJ6FJ6eIs6eeWI8SHLb9DpS6UhJ73E48Wj4Co/kGthxjipYFN/sJdtn10Qcz660sy5X4lp0BQjPGaqNWhDPJ4nUldmDsJAhOtkSVzdyxnuTEFUaTOAgq8/ZIkwpAhRWefBYjkvLBgUFLOmpyXAz4bXQ5veBv6cKM+uoCxAlRbYphGNEPkAb8n7Uyqka3HY+dIG3TrkyfkHlc5wBu6+IzG8QOyzfxUccS6FqyAQM54/EQX54Vv/ACURFJjdy1crSFAYqj1PEHBuBsU0TJxXeykI0l90UuP6xDy8EbHIntkkMT4KVzt2B6y4q4oSa7yMrCBk0E8epgimPhhjY8wK/Pma1ODCjjgIdELze8Ah3GWygkbi5l6RSxu5HZI6GwVBS5khCnVTjD9pJPO4TDWjAkRIyT0QEKaEAfz6JKmxH+5ufL1/Ch+/SRSCcEvlf7C5KrJSnZT2hJPBcptZmZvOVpq9OjzTHgt8dBamWBD5M6JJo+PSc4+E4+wk7ngRVTUeBO3cYkLEU=
