language: node_js
node_js:
- '12'
- '14'
services:
- redis-server
script:
- echo 'Starting'
- npm install
- echo 'Testing'
- npm test
deploy:
  provider: heroku
  apy_key:
    secure: 8b1012e7-a617-42d6-af3e-6efd65d0b4fa
    app : lab5cmrt