language: node_js
node_js:
- '12'
- '14'
services:
- redis-server
script:
- echo 'Starting'
- npm install
- echo 'Testing'
- npm test

deploy:
  provider: heroku
  api_key:
    secure: Axq9dY1sit+epQ+l6XgsGbjOuWE7S0kIfC8Rmr42udi6zhYUUoz8VCOO7FtHVFbpSdkAerQtnRXKmaEVsSpZZexfozQd2aVHRdgeaZNKom/nAqjFSobHJkNDC3QC6Ppx2wsoky8DUBWPoPrVoH0h0ET3zWlSoXt7HkzwLTHPtiWIuN7mQUfLi7j4FWP+rFTUySSNZQle2bBB4In10MHYwfuHnJB7iTCF5/qi+3I1Jprcc2xpMVrdM/r5fCo37pUDa6acla6wsAXks6PxWXxOW3mtJf0D6l1NGnNJMhquDFOETq3Q0lrM+lrImhOhUVcdNf/lwcCaym8L5NUA1TfsI6GeM+WbiwrWBxXvr4RWQdJQPoJvHmv0pgtJ6Kq1yi57rcU61uiVUbnsXis2mrcquzqesuq+AfxMPEWfRxpdFApVQxbzQp0b9Moo2RtECuk8TBJcZ0221LZeaO7Se/QXaRE3g8CwkBIgs9j6pdjUQS2MT2OEdYuKyBh2FA825/xcwKPzDSIBz79VaZV1Mbiig0dQlj6sJdnV6wC8QNKn8HPagigtzpziFicR7fHuKn5qHUVSJYAs0G5WLZgh3zHSf2EY8TudjfSOqBkLhnInCGdq7chT0igC+poYDzg7cY/O24DhpuSPxIeC8FsQEhlKdSzR6GNBaVBQhXCzvk3QRlc=
  app: lab5cmrt
  on:
    repo: leacmrt/LAB5